//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbVinhosEFA
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Vinho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vinho()
        {
            this.VinhoCastas = new HashSet<VinhoCasta>();
            this.VinhoEnologoes = new HashSet<VinhoEnologo>();
            this.VinhoProvas = new HashSet<VinhoProva>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Foto { get; set; }
        public Nullable<int> Regiao { get; set; }
        public Nullable<int> Produtor { get; set; }
        public Nullable<int> TipoVinho { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> TeorAlcoolico { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Utilizador { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Produtor Produtor1 { get; set; }
        public virtual Regiao Regiao1 { get; set; }
        public virtual TipoVinho TipoVinho1 { get; set; }
        public virtual Utilizador Utilizador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinhoCasta> VinhoCastas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinhoEnologo> VinhoEnologoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinhoProva> VinhoProvas { get; set; }
    }
}
