//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbVinhosEFA
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class VinhoCasta
    {
        public int Id { get; set; }
        public Nullable<int> Vinho { get; set; }
        public Nullable<int> Casta { get; set; }
    
        public virtual Casta Casta1 { get; set; }
        public virtual Vinho Vinho1 { get; set; }
    }
}
