//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbVinhosEFA
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class VinhoProva
    {
        public int Id { get; set; }
        public Nullable<int> Vinho { get; set; }
        public Nullable<int> Utilizador { get; set; }
        public string Comentario { get; set; }
        public Nullable<byte> Classificacao { get; set; }
    
        public virtual Utilizador Utilizador1 { get; set; }
        public virtual Vinho Vinho1 { get; set; }
    }
}
